### ISSUE TITLE
'here' in the demo diffusion constants.ipynb not working

### ISSUE THREAD

**Issue by IQraQasim10** [schuetzgroup/sdt-python-tutorials#1]
Hey, Thank you for a great contribution, I intend to practice your diffusion contants.ipyng file from the sdt-python tutorials but while following the directions i see that the button under the text 'download example data' is not working. 

It would be great if you can solve it:)

**Comment by lschr** [comment]
Hey, thanks for your report and sorry for the delay in getting back to you.

The link works for me in Jupyter Lab (i.e., download the notebook and open it on your computer in Jupyter Lab). When displaying in Github, it works (for me) by clicking “open in new tab”. Only normal clicking on the link in Github indeed does not work, making it seem like an issue (or maybe security precaution) with Github. Given the easy workarounds I don't think there is a need for further investigation (please re-open if you disagree).
